set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(ARM_NONE_EABI_PREFIX "arm-none-eabi" CACHE STRING "GNU Arm Embedded toolchain prefix")

find_program(ARM_NONE_EABI_GCC NAMES ${ARM_NONE_EABI_PREFIX}-gcc REQUIRED)
find_program(ARM_NONE_EABI_GXX NAMES ${ARM_NONE_EABI_PREFIX}-g++ REQUIRED)
find_program(ARM_NONE_EABI_AR NAMES ${ARM_NONE_EABI_PREFIX}-ar ${ARM_NONE_EABI_PREFIX}-gcc-ar ar REQUIRED)
find_program(ARM_NONE_EABI_RANLIB NAMES ${ARM_NONE_EABI_PREFIX}-ranlib ranlib REQUIRED)
find_program(ARM_NONE_EABI_OBJCOPY NAMES ${ARM_NONE_EABI_PREFIX}-objcopy REQUIRED)
find_program(ARM_NONE_EABI_SIZE NAMES ${ARM_NONE_EABI_PREFIX}-size REQUIRED)

set(CMAKE_C_COMPILER "${ARM_NONE_EABI_GCC}")
set(CMAKE_CXX_COMPILER "${ARM_NONE_EABI_GXX}")
set(CMAKE_ASM_COMPILER "${ARM_NONE_EABI_GCC}")
set(CMAKE_AR "${ARM_NONE_EABI_AR}")
set(CMAKE_RANLIB "${ARM_NONE_EABI_RANLIB}")
set(CMAKE_OBJCOPY "${ARM_NONE_EABI_OBJCOPY}")
set(CMAKE_SIZE "${ARM_NONE_EABI_SIZE}")
set(CMAKE_EXECUTABLE_SUFFIX ".elf")

set(ARM_CPU_FLAGS "-mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard")
set(ARM_COMMON_FLAGS "${ARM_CPU_FLAGS} -ffunction-sections -fdata-sections")

set(CMAKE_C_FLAGS_INIT "${ARM_COMMON_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT
  "${ARM_COMMON_FLAGS} -fno-exceptions -fno-rtti -fno-use-cxa-atexit"
)
set(CMAKE_ASM_FLAGS_INIT "${ARM_CPU_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${ARM_CPU_FLAGS} -Wl,--gc-sections")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
